version: "3.8"

services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    hostname: rabbitmq_host
    ports:
      - "5672:5672" # RabbitMQ
      - "15672:15672" # Management UI
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  training_trigger_api:
    build:
      context: ./training_trigger_api
    ports:
      - "5000:5000"
    environment:
      FLASK_ENV: development
      RABBITMQ_HOST: rabbitmq_host
      RABBITMQ_PORT: 5672
      RABBITMQ_USER: guest
      RABBITMQ_PASS: guest
    env_file:
      - .env.example

    depends_on:
      - rabbitmq
    volumes:
      - ./training_trigger_api:/app
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/"]
      interval: 10s
      timeout: 5s
      retries: 5

  retraining_worker:
    build: ./retraining_worker
    environment:
      RABBITMQ_HOST: rabbitmq_host
      RABBITMQ_PORT: 5672
      RABBITMQ_USER: guest
      RABBITMQ_PASS: guest
    depends_on:
      - rabbitmq
    volumes:
      - ./retraining_worker:/app
      - ./data:/app/data

volumes:
  rabbitmq_data:
